export const IDX_STOCKS = [
  { symbol: 'AALI', name: 'Astra Agro Lestari Tbk.' },
  { symbol: 'ABBA', name: 'Mahaka Media Tbk.' },
  { symbol: 'ABDA', name: 'Asuransi Bina Dana Arta Tbk.' },
  { symbol: 'ABMM', name: 'ABM Investama Tbk.' },
  { symbol: 'ACES', name: 'Aspirasi Hidup Indonesia Tbk.' },
  { symbol: 'ACST', name: 'Acset Indonusa Tbk.' },
  { symbol: 'ADES', name: 'Akasha Wira International Tbk.' },
  { symbol: 'ADHI', name: 'Adhi Karya (Persero) Tbk.' },
  { symbol: 'ADMF', name: 'Adira Dinamika Multi Finance T' },
  { symbol: 'ADMG', name: 'Polychem Indonesia Tbk' },
  { symbol: 'ADRO', name: 'Alamtri Resources Indonesia Tb' },
  { symbol: 'AGII', name: 'Samator Indo Gas Tbk.' },
  { symbol: 'AGRO', name: 'Bank Raya Indonesia Tbk.' },
  { symbol: 'AGRS', name: 'Bank IBK Indonesia Tbk.' },
  { symbol: 'AHAP', name: 'Asuransi Harta Aman Pratama Tb' },
  { symbol: 'AIMS', name: 'Artha Mahiya Investama Tbk.' },
  { symbol: 'AISA', name: 'FKS Food Sejahtera Tbk.' },
  { symbol: 'AKKU', name: 'Anugerah Kagum Karya Utama Tbk' },
  { symbol: 'AKPI', name: 'Argha Karya Prima Industry Tbk' },
  { symbol: 'AKRA', name: 'AKR Corporindo Tbk.' },
  { symbol: 'AKSI', name: 'Mineral Sumberdaya Mandiri Tbk' },
  { symbol: 'ALDO', name: 'Alkindo Naratama Tbk.' },
  { symbol: 'ALKA', name: 'Alakasa Industrindo Tbk' },
  { symbol: 'ALMI', name: 'Alumindo Light Metal Industry ' },
  { symbol: 'ALTO', name: 'Tri Banyan Tirta Tbk.' },
  { symbol: 'AMAG', name: 'Asuransi Multi Artha Guna Tbk.' },
  { symbol: 'AMFG', name: 'Asahimas Flat Glass Tbk.' },
  { symbol: 'AMIN', name: 'Ateliers Mecaniques D Indonesi' },
  { symbol: 'AMRT', name: 'Sumber Alfaria Trijaya Tbk.' },
  { symbol: 'ANJT', name: 'Austindo Nusantara Jaya Tbk.' },
  { symbol: 'ANTM', name: 'Aneka Tambang Tbk.' },
  { symbol: 'APEX', name: 'Apexindo Pratama Duta Tbk.' },
  { symbol: 'APIC', name: 'Pacific Strategic Financial Tb' },
  { symbol: 'APII', name: 'Arita Prima Indonesia Tbk.' },
  { symbol: 'APLI', name: 'Asiaplast Industries Tbk.' },
  { symbol: 'APLN', name: 'Agung Podomoro Land Tbk.' },
  { symbol: 'ARGO', name: 'Argo Pantes Tbk' },
  { symbol: 'ARII', name: 'Atlas Resources Tbk.' },
  { symbol: 'ARNA', name: 'Arwana Citramulia Tbk.' },
  { symbol: 'ARTA', name: 'Arthavest Tbk' },
  { symbol: 'ARTI', name: 'Ratu Prabu Energi Tbk' },
  { symbol: 'ARTO', name: 'Bank Jago Tbk.' },
  { symbol: 'ASBI', name: 'Asuransi Bintang Tbk.' },
  { symbol: 'ASDM', name: 'Asuransi Dayin Mitra Tbk.' },
  { symbol: 'ASGR', name: 'Astra Graphia Tbk.' },
  { symbol: 'ASII', name: 'Astra International Tbk.' },
  { symbol: 'ASJT', name: 'Asuransi Jasa Tania Tbk.' },
  { symbol: 'ASMI', name: 'Asuransi Maximus Graha Persada' },
  { symbol: 'ASRI', name: 'Alam Sutera Realty Tbk.' },
  { symbol: 'ASRM', name: 'Asuransi Ramayana Tbk.' },
  { symbol: 'ASSA', name: 'Adi Sarana Armada Tbk.' },
  { symbol: 'ATIC', name: 'Anabatic Technologies Tbk.' },
  { symbol: 'AUTO', name: 'Astra Otoparts Tbk.' },
  { symbol: 'BABP', name: 'Bank MNC Internasional Tbk.' },
  { symbol: 'BACA', name: 'Bank Capital Indonesia Tbk.' },
  { symbol: 'BAJA', name: 'Saranacentral Bajatama Tbk.' },
  { symbol: 'BALI', name: 'Bali Towerindo Sentra Tbk.' },
  { symbol: 'BAPA', name: 'Bekasi Asri Pemula Tbk.' },
  { symbol: 'BATA', name: 'Sepatu Bata Tbk.' },
  { symbol: 'BAYU', name: 'Bayu Buana Tbk' },
  { symbol: 'BBCA', name: 'Bank Central Asia Tbk.' },
  { symbol: 'BBHI', name: 'Allo Bank Indonesia Tbk.' },
  { symbol: 'BBKP', name: 'Bank KB Bukopin Tbk.' },
  { symbol: 'BBLD', name: 'Buana Finance Tbk.' },
  { symbol: 'BBMD', name: 'Bank Mestika Dharma Tbk.' },
  { symbol: 'BBNI', name: 'Bank Negara Indonesia (Persero' },
  { symbol: 'BBRI', name: 'Bank Rakyat Indonesia (Persero' },
  { symbol: 'BBRM', name: 'Pelayaran Nasional Bina Buana ' },
  { symbol: 'BBTN', name: 'Bank Tabungan Negara (Persero)' },
  { symbol: 'BBYB', name: 'Bank Neo Commerce Tbk.' },
  { symbol: 'BCAP', name: 'MNC Kapital Indonesia Tbk.' },
  { symbol: 'BCIC', name: 'Bank JTrust Indonesia Tbk.' },
  { symbol: 'BCIP', name: 'Bumi Citra Permai Tbk.' },
  { symbol: 'BDMN', name: 'Bank Danamon Indonesia Tbk.' },
  { symbol: 'BEKS', name: 'Bank Pembangunan Daerah Banten' },
  { symbol: 'BEST', name: 'Bekasi Fajar Industrial Estate' },
  { symbol: 'BFIN', name: 'BFI Finance  Indonesia Tbk.' },
  { symbol: 'BGTG', name: 'Bank Ganesha Tbk.' },
  { symbol: 'BHIT', name: 'MNC Asia Holding Tbk.' },
  { symbol: 'BIKA', name: 'Binakarya Jaya Abadi Tbk.' },
  { symbol: 'BIMA', name: 'Primarindo Asia Infrastructure' },
  { symbol: 'BINA', name: 'Bank Ina Perdana Tbk.' },
  { symbol: 'BIPI', name: 'Astrindo Nusantara Infrastrukt' },
  { symbol: 'BIPP', name: 'Bhuwanatala Indah Permai Tbk.' },
  { symbol: 'BIRD', name: 'Blue Bird Tbk.' },
  { symbol: 'BISI', name: 'BISI International Tbk.' },
  { symbol: 'BJBR', name: 'Bank Pembangunan Daerah Jawa B' },
  { symbol: 'BJTM', name: 'Bank Pembangunan Daerah Jawa T' },
  { symbol: 'BKDP', name: 'Bukit Darmo Property Tbk' },
  { symbol: 'BKSL', name: 'Sentul City Tbk.' },
  { symbol: 'BKSW', name: 'Bank QNB Indonesia Tbk.' },
  { symbol: 'BLTA', name: 'Berlian Laju Tanker Tbk' },
  { symbol: 'BLTZ', name: 'Graha Layar Prima Tbk.' },
  { symbol: 'BMAS', name: 'Bank Maspion Indonesia Tbk.' },
  { symbol: 'BMRI', name: 'Bank Mandiri (Persero) Tbk.' },
  { symbol: 'BMSR', name: 'Bintang Mitra Semestaraya Tbk' },
  { symbol: 'BMTR', name: 'Global Mediacom Tbk.' },
  { symbol: 'BNBA', name: 'Bank Bumi Arta Tbk.' },
  { symbol: 'BNBR', name: 'Bakrie & Brothers Tbk' },
  { symbol: 'BNGA', name: 'Bank CIMB Niaga Tbk.' },
  { symbol: 'BNII', name: 'Bank Maybank Indonesia Tbk.' },
  { symbol: 'BNLI', name: 'Bank Permata Tbk.' },
  { symbol: 'BOLT', name: 'Garuda Metalindo Tbk.' },
  { symbol: 'BPFI', name: 'Woori Finance Indonesia Tbk.' },
  { symbol: 'BPII', name: 'Batavia Prosperindo Internasio' },
  { symbol: 'BRAM', name: 'Indo Kordsa Tbk.' },
  { symbol: 'BRMS', name: 'Bumi Resources Minerals Tbk.' },
  { symbol: 'BRNA', name: 'Berlina Tbk.' },
  { symbol: 'BRPT', name: 'Barito Pacific Tbk.' },
  { symbol: 'BSDE', name: 'Bumi Serpong Damai Tbk.' },
  { symbol: 'BSIM', name: 'Bank Sinarmas Tbk.' },
  { symbol: 'BSSR', name: 'Baramulti Suksessarana Tbk.' },
  { symbol: 'BSWD', name: 'Bank Of India Indonesia Tbk.' },
  { symbol: 'BTEK', name: 'Bumi Teknokultura Unggul Tbk' },
  { symbol: 'BTEL', name: 'Bakrie Telecom Tbk.' },
  { symbol: 'BTON', name: 'Betonjaya Manunggal Tbk.' },
  { symbol: 'BTPN', name: 'Bank SMBC Indonesia Tbk.' },
  { symbol: 'BUDI', name: 'Budi Starch & Sweetener Tbk.' },
  { symbol: 'BUKK', name: 'Bukaka Teknik Utama Tbk.' },
  { symbol: 'BULL', name: 'Buana Lintas Lautan Tbk.' },
  { symbol: 'BUMI', name: 'Bumi Resources Tbk.' },
  { symbol: 'BUVA', name: 'Bukit Uluwatu Villa Tbk.' },
  { symbol: 'BVIC', name: 'Bank Victoria International Tb' },
  { symbol: 'BWPT', name: 'Eagle High Plantations Tbk.' },
  { symbol: 'BYAN', name: 'Bayan Resources Tbk.' },
  { symbol: 'CANI', name: 'Capitol Nusantara Indonesia Tb' },
  { symbol: 'CASS', name: 'Cardig Aero Services Tbk.' },
  { symbol: 'CEKA', name: 'Wilmar Cahaya Indonesia Tbk.' },
  { symbol: 'CENT', name: 'Centratama Telekomunikasi Indo' },
  { symbol: 'CFIN', name: 'Clipan Finance Indonesia Tbk.' },
  { symbol: 'CINT', name: 'Chitose Internasional Tbk.' },
  { symbol: 'CITA', name: 'Cita Mineral Investindo Tbk.' },
  { symbol: 'CLPI', name: 'Colorpak Indonesia Tbk.' },
  { symbol: 'CMNP', name: 'Citra Marga Nusaphala Persada ' },
  { symbol: 'CMPP', name: 'AirAsia Indonesia Tbk.' },
  { symbol: 'CNKO', name: 'Exploitasi Energi Indonesia Tb' },
  { symbol: 'CNTX', name: 'Century Textile Industry Tbk.' },
  { symbol: 'COWL', name: 'Cowell Development Tbk.' },
  { symbol: 'CPIN', name: 'Charoen Pokphand Indonesia Tbk' },
  { symbol: 'CPRO', name: 'Central Proteina Prima Tbk.' },
  { symbol: 'CSAP', name: 'Catur Sentosa Adiprana Tbk.' },
  { symbol: 'CTBN', name: 'Citra Tubindo Tbk.' },
  { symbol: 'CTRA', name: 'Ciputra Development Tbk.' },
  { symbol: 'CTTH', name: 'Citatah Tbk.' },
  { symbol: 'DART', name: 'Duta Anggada Realty Tbk.' },
  { symbol: 'DEFI', name: 'Danasupra Erapacific Tbk.' },
  { symbol: 'DEWA', name: 'Darma Henwa Tbk' },
  { symbol: 'DGIK', name: 'Nusa Konstruksi Enjiniring Tbk' },
  { symbol: 'DILD', name: 'Intiland Development Tbk.' },
  { symbol: 'DKFT', name: 'Central Omega Resources Tbk.' },
  { symbol: 'DLTA', name: 'Delta Djakarta Tbk.' },
  { symbol: 'DMAS', name: 'Puradelta Lestari Tbk.' },
  { symbol: 'DNAR', name: 'Bank Oke Indonesia Tbk.' },
  { symbol: 'DNET', name: 'Indoritel Makmur Internasional' },
  { symbol: 'DOID', name: 'Delta Dunia Makmur Tbk.' },
  { symbol: 'DPNS', name: 'Duta Pertiwi Nusantara Tbk.' },
  { symbol: 'DSFI', name: 'Dharma Samudera Fishing Indust' },
  { symbol: 'DSNG', name: 'Dharma Satya Nusantara Tbk.' },
  { symbol: 'DSSA', name: 'Dian Swastatika Sentosa Tbk' },
  { symbol: 'DUTI', name: 'Duta Pertiwi Tbk' },
  { symbol: 'DVLA', name: 'Darya-Varia Laboratoria Tbk.' },
  { symbol: 'DYAN', name: 'Dyandra Media International Tb' },
  { symbol: 'ECII', name: 'Electronic City Indonesia Tbk.' },
  { symbol: 'EKAD', name: 'Ekadharma International Tbk.' },
  { symbol: 'ELSA', name: 'Elnusa Tbk.' },
  { symbol: 'ELTY', name: 'Bakrieland Development Tbk.' },
  { symbol: 'EMDE', name: 'Megapolitan Developments Tbk.' },
  { symbol: 'EMTK', name: 'Elang Mahkota Teknologi Tbk.' },
  { symbol: 'ENRG', name: 'Energi Mega Persada Tbk.' },
  { symbol: 'EPMT', name: 'Enseval Putera Megatrading Tbk' },
  { symbol: 'ERAA', name: 'Erajaya Swasembada Tbk.' },
  { symbol: 'ERTX', name: 'Eratex Djaja Tbk.' },
  { symbol: 'ESSA', name: 'ESSA Industries Indonesia Tbk.' },
  { symbol: 'ESTI', name: 'Ever Shine Tex Tbk.' },
  { symbol: 'ETWA', name: 'Eterindo Wahanatama Tbk' },
  { symbol: 'EXCL', name: 'XL Axiata Tbk.' },
  { symbol: 'FAST', name: 'Fast Food Indonesia Tbk.' },
  { symbol: 'FASW', name: 'Fajar Surya Wisesa Tbk.' },
  { symbol: 'FISH', name: 'FKS Multi Agro Tbk.' },
  { symbol: 'FMII', name: 'Fortune Mate Indonesia Tbk' },
  { symbol: 'FORU', name: 'Fortune Indonesia Tbk' },
  { symbol: 'FPNI', name: 'Lotte Chemical Titan Tbk.' },
  { symbol: 'FREN', name: 'Smartfren Telecom Tbk.' },
  { symbol: 'GAMA', name: 'Aksara Global Development Tbk.' },
  { symbol: 'GDST', name: 'Gunawan Dianjaya Steel Tbk.' },
  { symbol: 'GDYR', name: 'Goodyear Indonesia Tbk.' },
  { symbol: 'GEMA', name: 'Gema Grahasarana Tbk.' },
  { symbol: 'GEMS', name: 'Golden Energy Mines Tbk.' },
  { symbol: 'GGRM', name: 'Gudang Garam Tbk.' },
  { symbol: 'GIAA', name: 'Garuda Indonesia (Persero) Tbk' },
  { symbol: 'GJTL', name: 'Gajah Tunggal Tbk.' },
  { symbol: 'GLOB', name: 'Globe Kita Terang Tbk.' },
  { symbol: 'GMTD', name: 'Gowa Makassar Tourism Developm' },
  { symbol: 'GOLD', name: 'Visi Telekomunikasi Infrastruk' },
  { symbol: 'GOLL', name: 'Golden Plantation Tbk.' },
  { symbol: 'GPRA', name: 'Perdana Gapuraprima Tbk.' },
  { symbol: 'GSMF', name: 'Equity Development Investment ' },
  { symbol: 'GTBO', name: 'Garda Tujuh Buana Tbk' },
  { symbol: 'GWSA', name: 'Greenwood Sejahtera Tbk.' },
  { symbol: 'GZCO', name: 'Gozco Plantations Tbk.' },
  { symbol: 'HADE', name: 'Himalaya Energi Perkasa Tbk.' },
  { symbol: 'HDFA', name: 'Radana Bhaskara Finance Tbk.' },
  { symbol: 'HDTX', name: 'Panasia Indo Resources Tbk.' },
  { symbol: 'HERO', name: 'DFI Retail Nusantara Tbk.' },
  { symbol: 'HEXA', name: 'Hexindo Adiperkasa Tbk.' },
  { symbol: 'HITS', name: 'Humpuss Intermoda Transportasi' },
  { symbol: 'HMSP', name: 'H.M. Sampoerna Tbk.' },
  { symbol: 'HOME', name: 'Hotel Mandarine Regency Tbk.' },
  { symbol: 'HOTL', name: 'Saraswati Griya Lestari Tbk.' },
  { symbol: 'HRUM', name: 'Harum Energy Tbk.' },
  { symbol: 'IATA', name: 'MNC Energy Investments Tbk.' },
  { symbol: 'IBFN', name: 'Intan Baru Prana Tbk.' },
  { symbol: 'IBST', name: 'Inti Bangun Sejahtera Tbk.' },
  { symbol: 'ICBP', name: 'Indofood CBP Sukses Makmur Tbk' },
  { symbol: 'ICON', name: 'Island Concepts Indonesia Tbk.' },
  { symbol: 'IGAR', name: 'Champion Pacific Indonesia Tbk' },
  { symbol: 'IIKP', name: 'Inti Agri Resources Tbk' },
  { symbol: 'IKAI', name: 'Intikeramik Alamasri Industri ' },
  { symbol: 'IKBI', name: 'Sumi Indo Kabel Tbk.' },
  { symbol: 'IMAS', name: 'Indomobil Sukses Internasional' },
  { symbol: 'IMJS', name: 'Indomobil Multi Jasa Tbk.' },
  { symbol: 'IMPC', name: 'Impack Pratama Industri Tbk.' },
  { symbol: 'INAF', name: 'Indofarma Tbk.' },
  { symbol: 'INAI', name: 'Indal Aluminium Industry Tbk.' },
  { symbol: 'INCI', name: 'Intanwijaya Internasional Tbk' },
  { symbol: 'INCO', name: 'Vale Indonesia Tbk.' },
  { symbol: 'INDF', name: 'Indofood Sukses Makmur Tbk.' },
  { symbol: 'INDR', name: 'Indo-Rama Synthetics Tbk.' },
  { symbol: 'INDS', name: 'Indospring Tbk.' },
  { symbol: 'INDX', name: 'Tanah Laut Tbk' },
  { symbol: 'INDY', name: 'Indika Energy Tbk.' },
  { symbol: 'INKP', name: 'Indah Kiat Pulp & Paper Tbk.' },
  { symbol: 'INPC', name: 'Bank Artha Graha Internasional' },
  { symbol: 'INPP', name: 'Indonesian Paradise Property T' },
  { symbol: 'INRU', name: 'Toba Pulp Lestari Tbk.' },
  { symbol: 'INTA', name: 'Intraco Penta Tbk.' },
  { symbol: 'INTD', name: 'Inter Delta Tbk' },
  { symbol: 'INTP', name: 'Indocement Tunggal Prakarsa Tb' },
  { symbol: 'IPOL', name: 'Indopoly Swakarsa Industry Tbk' },
  { symbol: 'ISAT', name: 'Indosat Tbk.' },
  { symbol: 'ISSP', name: 'Steel Pipe Industry of Indones' },
  { symbol: 'ITMA', name: 'Sumber Energi Andalan Tbk.' },
  { symbol: 'ITMG', name: 'Indo Tambangraya Megah Tbk.' },
  { symbol: 'JAWA', name: 'Jaya Agra Wattie Tbk.' },
  { symbol: 'JECC', name: 'Jembo Cable Company Tbk.' },
  { symbol: 'JIHD', name: 'Jakarta International Hotels &' },
  { symbol: 'JKON', name: 'Jaya Konstruksi Manggala Prata' },
  { symbol: 'JKSW', name: 'Jakarta Kyoei Steel Works Tbk.' },
  { symbol: 'JPFA', name: 'Japfa Comfeed Indonesia Tbk.' },
  { symbol: 'JRPT', name: 'Jaya Real Property Tbk.' },
  { symbol: 'JSMR', name: 'Jasa Marga (Persero) Tbk.' },
  { symbol: 'JSPT', name: 'Jakarta Setiabudi Internasiona' },
  { symbol: 'JTPE', name: 'Jasuindo Tiga Perkasa Tbk.' },
  { symbol: 'KAEF', name: 'Kimia Farma Tbk.' },
  { symbol: 'KARW', name: 'Meratus Jasa Prima Tbk.' },
  { symbol: 'KBLI', name: 'KMI Wire & Cable Tbk.' },
  { symbol: 'KBLM', name: 'Kabelindo Murni Tbk.' },
  { symbol: 'KBLV', name: 'First Media Tbk.' },
  { symbol: 'KBRI', name: 'Kertas Basuki Rachmat Indonesi' },
  { symbol: 'KDSI', name: 'Kedawung Setia Industrial Tbk.' },
  { symbol: 'KIAS', name: 'Keramika Indonesia Assosiasi T' },
  { symbol: 'KICI', name: 'Kedaung Indah Can Tbk' },
  { symbol: 'KIJA', name: 'Kawasan Industri Jababeka Tbk.' },
  { symbol: 'KKGI', name: 'Resource Alam Indonesia Tbk.' },
  { symbol: 'KLBF', name: 'Kalbe Farma Tbk.' },
  { symbol: 'KOBX', name: 'Kobexindo Tractors Tbk.' },
  { symbol: 'KOIN', name: 'Kokoh Inti Arebama Tbk' },
  { symbol: 'KONI', name: 'Perdana Bangun Pusaka Tbk' },
  { symbol: 'KOPI', name: 'Mitra Energi Persada Tbk.' },
  { symbol: 'KPIG', name: 'MNC Land Tbk.' },
  { symbol: 'KRAH', name: 'Grand Kartech Tbk.' },
  { symbol: 'KRAS', name: 'Krakatau Steel (Persero) Tbk.' },
  { symbol: 'KREN', name: 'Quantum Clovera Investama Tbk.' },
  { symbol: 'LAPD', name: 'Leyand International Tbk.' },
  { symbol: 'LCGP', name: 'Eureka Prima Jakarta Tbk.' },
  { symbol: 'LEAD', name: 'Logindo Samudramakmur Tbk.' },
  { symbol: 'LINK', name: 'Link Net Tbk.' },
  { symbol: 'LION', name: 'Lion Metal Works Tbk.' },
  { symbol: 'LMAS', name: 'Limas Indonesia Makmur Tbk' },
  { symbol: 'LMPI', name: 'Langgeng Makmur Industri Tbk.' },
  { symbol: 'LMSH', name: 'Lionmesh Prima Tbk.' },
  { symbol: 'LPCK', name: 'Lippo Cikarang Tbk' },
  { symbol: 'LPGI', name: 'Lippo General Insurance Tbk.' },
  { symbol: 'LPIN', name: 'Multi Prima Sejahtera Tbk' },
  { symbol: 'LPKR', name: 'Lippo Karawaci Tbk.' },
  { symbol: 'LPLI', name: 'Star Pacific Tbk' },
  { symbol: 'LPPF', name: 'Matahari Department Store Tbk.' },
  { symbol: 'LPPS', name: 'Lenox Pasifik Investama Tbk.' },
  { symbol: 'LRNA', name: 'Eka Sari Lorena Transport Tbk.' },
  { symbol: 'LSIP', name: 'PP London Sumatra Indonesia Tb' },
  { symbol: 'LTLS', name: 'Lautan Luas Tbk.' },
  { symbol: 'MAGP', name: 'Multi Agro Gemilang Plantation' },
  { symbol: 'MAIN', name: 'Malindo Feedmill Tbk.' },
  { symbol: 'MAMI', name: 'Mas Murni Indonesia Tbk' },
  { symbol: 'MAPI', name: 'Mitra Adiperkasa Tbk.' },
  { symbol: 'MASA', name: 'Multistrada Arah Sarana Tbk.' },
  { symbol: 'MAYA', name: 'Bank Mayapada Internasional Tb' },
  { symbol: 'MBAP', name: 'Mitrabara Adiperdana Tbk.' },
  { symbol: 'MBSS', name: 'Mitrabahtera Segara Sejati Tbk' },
  { symbol: 'MBTO', name: 'Martina Berto Tbk.' },
  { symbol: 'MCOR', name: 'Bank China Construction Bank I' },
  { symbol: 'MDIA', name: 'Intermedia Capital Tbk.' },
  { symbol: 'MDKA', name: 'Merdeka Copper Gold Tbk.' },
  { symbol: 'MDLN', name: 'Modernland Realty Tbk.' },
  { symbol: 'MDRN', name: 'Modern Internasional Tbk.' },
  { symbol: 'MEDC', name: 'Medco Energi Internasional Tbk' },
  { symbol: 'MEGA', name: 'Bank Mega Tbk.' },
  { symbol: 'MERK', name: 'Merck Tbk.' },
  { symbol: 'META', name: 'Nusantara Infrastructure Tbk.' },
  { symbol: 'MFIN', name: 'Mandala Multifinance Tbk.' },
  { symbol: 'MFMI', name: 'Multifiling Mitra Indonesia Tb' },
  { symbol: 'MGNA', name: 'Magna Investama Mandiri Tbk.' },
  { symbol: 'MICE', name: 'Multi Indocitra Tbk.' },
  { symbol: 'MIDI', name: 'Midi Utama Indonesia Tbk.' },
  { symbol: 'MIKA', name: 'Mitra Keluarga Karyasehat Tbk.' },
  { symbol: 'MIRA', name: 'Mitra International Resources ' },
  { symbol: 'MITI', name: 'Mitra Investindo Tbk.' },
  { symbol: 'MKPI', name: 'Metropolitan Kentjana Tbk.' },
  { symbol: 'MLBI', name: 'Multi Bintang Indonesia Tbk.' },
  { symbol: 'MLIA', name: 'Mulia Industrindo Tbk' },
  { symbol: 'MLPL', name: 'Multipolar Tbk.' },
  { symbol: 'MLPT', name: 'Multipolar Technology Tbk.' },
  { symbol: 'MMLP', name: 'Mega Manunggal Property Tbk.' },
  { symbol: 'MNCN', name: 'Media Nusantara Citra Tbk.' },
  { symbol: 'MPMX', name: 'Mitra Pinasthika Mustika Tbk.' },
  { symbol: 'MPPA', name: 'Matahari Putra Prima Tbk.' },
  { symbol: 'MRAT', name: 'Mustika Ratu Tbk.' },
  { symbol: 'MREI', name: 'Maskapai Reasuransi Indonesia ' },
  { symbol: 'MSKY', name: 'MNC Sky Vision Tbk.' },
  { symbol: 'MTDL', name: 'Metrodata Electronics Tbk.' },
  { symbol: 'MTFN', name: 'Capitalinc Investment Tbk.' },
  { symbol: 'MTLA', name: 'Metropolitan Land Tbk.' },
  { symbol: 'MTSM', name: 'Metro Realty Tbk.' },
  { symbol: 'MYOH', name: 'Samindo Resources Tbk.' },
  { symbol: 'MYOR', name: 'Mayora Indah Tbk.' },
  { symbol: 'MYRX', name: 'Hanson International Tbk.' },
  { symbol: 'MYTX', name: 'Asia Pacific Investama Tbk.' },
  { symbol: 'NELY', name: 'Pelayaran Nelly Dwi Putri Tbk.' },
  { symbol: 'NIKL', name: 'Pelat Timah Nusantara Tbk.' },
  { symbol: 'NIPS', name: 'Nipress Tbk.' },
  { symbol: 'NIRO', name: 'City Retail Developments Tbk.' },
  { symbol: 'NISP', name: 'Bank OCBC NISP Tbk.' },
  { symbol: 'NOBU', name: 'Bank Nationalnobu Tbk.' },
  { symbol: 'NRCA', name: 'Nusa Raya Cipta Tbk.' },
  { symbol: 'OCAP', name: 'Onix Capital Tbk.' },
  { symbol: 'OKAS', name: 'Ancora Indonesia Resources Tbk' },
  { symbol: 'OMRE', name: 'Indonesia Prima Property Tbk' },
  { symbol: 'PADI', name: 'Minna Padi Investama Sekuritas' },
  { symbol: 'PALM', name: 'Provident Investasi Bersama Tb' },
  { symbol: 'PANR', name: 'Panorama Sentrawisata Tbk.' },
  { symbol: 'PANS', name: 'Panin Sekuritas Tbk.' },
  { symbol: 'PBRX', name: 'Pan Brothers Tbk.' },
  { symbol: 'PDES', name: 'Destinasi Tirta Nusantara Tbk' },
  { symbol: 'PEGE', name: 'Panca Global Kapital Tbk.' },
  { symbol: 'PGAS', name: 'Perusahaan Gas Negara Tbk.' },
  { symbol: 'PGLI', name: 'Pembangunan Graha Lestari Inda' },
  { symbol: 'PICO', name: 'Pelangi Indah Canindo Tbk' },
  { symbol: 'PJAA', name: 'Pembangunan Jaya Ancol Tbk.' },
  { symbol: 'PKPK', name: 'Perdana Karya Perkasa Tbk' },
  { symbol: 'PLAS', name: 'Polaris Investama Tbk' },
  { symbol: 'PLIN', name: 'Plaza Indonesia Realty Tbk.' },
  { symbol: 'PNBN', name: 'Bank Pan Indonesia Tbk' },
  { symbol: 'PNBS', name: 'Bank Panin Dubai Syariah Tbk.' },
  { symbol: 'PNIN', name: 'Paninvest Tbk.' },
  { symbol: 'PNLF', name: 'Panin Financial Tbk.' },
  { symbol: 'PNSE', name: 'Pudjiadi & Sons Tbk.' },
  { symbol: 'POLY', name: 'Asia Pacific Fibers Tbk' },
  { symbol: 'POOL', name: 'Pool Advista Indonesia Tbk.' },
  { symbol: 'PPRO', name: 'PP Properti Tbk.' },
  { symbol: 'PRAS', name: 'Prima Alloy Steel Universal Tb' },
  { symbol: 'PSAB', name: 'J Resources Asia Pasifik Tbk.' },
  { symbol: 'PSDN', name: 'Prasidha Aneka Niaga Tbk' },
  { symbol: 'PSKT', name: 'Red Planet Indonesia Tbk.' },
  { symbol: 'PTBA', name: 'Bukit Asam Tbk.' },
  { symbol: 'PTIS', name: 'Indo Straits Tbk.' },
  { symbol: 'PTPP', name: 'PP (Persero) Tbk.' },
  { symbol: 'PTRO', name: 'Petrosea Tbk.' },
  { symbol: 'PTSN', name: 'Sat Nusapersada Tbk' },
  { symbol: 'PTSP', name: 'Pioneerindo Gourmet Internatio' },
  { symbol: 'PUDP', name: 'Pudjiadi Prestige Tbk.' },
  { symbol: 'PWON', name: 'Pakuwon Jati Tbk.' },
  { symbol: 'PYFA', name: 'Pyridam Farma Tbk' },
  { symbol: 'RAJA', name: 'Rukun Raharja Tbk.' },
  { symbol: 'RALS', name: 'Ramayana Lestari Sentosa Tbk.' },
  { symbol: 'RANC', name: 'Supra Boga Lestari Tbk.' },
  { symbol: 'RBMS', name: 'Ristia Bintang Mahkotasejati T' },
  { symbol: 'RDTX', name: 'Roda Vivatex Tbk' },
  { symbol: 'RELI', name: 'Reliance Sekuritas Indonesia T' },
  { symbol: 'RICY', name: 'Ricky Putra Globalindo Tbk' },
  { symbol: 'RIGS', name: 'Rig Tenders Indonesia Tbk.' },
  { symbol: 'RIMO', name: 'Rimo International Lestari Tbk' },
  { symbol: 'RODA', name: 'Pikko Land Development Tbk.' },
  { symbol: 'ROTI', name: 'Nippon Indosari Corpindo Tbk.' },
  { symbol: 'RUIS', name: 'Radiant Utama Interinsco Tbk.' },
  { symbol: 'SAFE', name: 'Steady Safe Tbk' },
  { symbol: 'SAME', name: 'Sarana Meditama Metropolitan T' },
  { symbol: 'SCCO', name: 'Supreme Cable Manufacturing & ' },
  { symbol: 'SCMA', name: 'Surya Citra Media Tbk.' },
  { symbol: 'SCPI', name: 'Organon Pharma Indonesia Tbk.' },
  { symbol: 'SDMU', name: 'Sidomulyo Selaras Tbk.' },
  { symbol: 'SDPC', name: 'Millennium Pharmacon Internati' },
  { symbol: 'SDRA', name: 'Bank Woori Saudara Indonesia 1' },
  { symbol: 'SGRO', name: 'Sampoerna Agro Tbk.' },
  { symbol: 'SHID', name: 'Hotel Sahid Jaya International' },
  { symbol: 'SIDO', name: 'Industri Jamu dan Farmasi Sido' },
  { symbol: 'SILO', name: 'Siloam International Hospitals' },
  { symbol: 'SIMA', name: 'Siwani Makmur Tbk' },
  { symbol: 'SIMP', name: 'Salim Ivomas Pratama Tbk.' },
  { symbol: 'SIPD', name: 'Sreeya Sewu Indonesia Tbk.' },
  { symbol: 'SKBM', name: 'Sekar Bumi Tbk.' },
  { symbol: 'SKLT', name: 'Sekar Laut Tbk.' },
  { symbol: 'SKYB', name: 'Northcliff Citranusa Indonesia' },
  { symbol: 'SMAR', name: 'Smart Tbk.' },
  { symbol: 'SMBR', name: 'Semen Baturaja Tbk.' },
  { symbol: 'SMCB', name: 'Solusi Bangun Indonesia Tbk.' },
  { symbol: 'SMDM', name: 'Suryamas Dutamakmur Tbk.' },
  { symbol: 'SMDR', name: 'Samudera Indonesia  Tbk.' },
  { symbol: 'SMGR', name: 'Semen Indonesia (Persero) Tbk.' },
  { symbol: 'SMMA', name: 'Sinarmas Multiartha Tbk.' },
  { symbol: 'SMMT', name: 'Golden Eagle Energy Tbk.' },
  { symbol: 'SMRA', name: 'Summarecon Agung Tbk.' },
  { symbol: 'SMRU', name: 'SMR Utama Tbk.' },
  { symbol: 'SMSM', name: 'Selamat Sempurna Tbk.' },
  { symbol: 'SOCI', name: 'Soechi Lines Tbk.' },
  { symbol: 'SONA', name: 'Sona Topas Tourism Industry Tb' },
  { symbol: 'SPMA', name: 'Suparma Tbk.' },
  { symbol: 'SQMI', name: 'Wilton Makmur Indonesia Tbk.' },
  { symbol: 'SRAJ', name: 'Sejahteraraya Anugrahjaya Tbk.' },
  { symbol: 'SRIL', name: 'Sri Rejeki Isman Tbk.' },
  { symbol: 'SRSN', name: 'Indo Acidatama Tbk' },
  { symbol: 'SRTG', name: 'Saratoga Investama Sedaya Tbk.' },
  { symbol: 'SSIA', name: 'Surya Semesta Internusa Tbk.' },
  { symbol: 'SSMS', name: 'Sawit Sumbermas Sarana Tbk.' },
  { symbol: 'SSTM', name: 'Sunson Textile Manufacture Tbk' },
  { symbol: 'STAR', name: 'Buana Artha Anugerah Tbk.' },
  { symbol: 'STTP', name: 'Siantar Top Tbk.' },
  { symbol: 'SUGI', name: 'Sugih Energy Tbk.' },
  { symbol: 'SULI', name: 'SLJ Global Tbk.' },
  { symbol: 'SUPR', name: 'Solusi Tunas Pratama Tbk.' },
  { symbol: 'TALF', name: 'Tunas Alfin Tbk.' },
  { symbol: 'TARA', name: 'Agung Semesta Sejahtera Tbk.' },
  { symbol: 'TAXI', name: 'Express Transindo Utama Tbk.' },
  { symbol: 'TBIG', name: 'Tower Bersama Infrastructure T' },
  { symbol: 'TBLA', name: 'Tunas Baru Lampung Tbk.' },
  { symbol: 'TBMS', name: 'Tembaga Mulia Semanan Tbk.' },
  { symbol: 'TCID', name: 'Mandom Indonesia Tbk.' },
  { symbol: 'TELE', name: 'Omni Inovasi Indonesia Tbk.' },
  { symbol: 'TFCO', name: 'Tifico Fiber Indonesia Tbk.' },
  { symbol: 'TGKA', name: 'Tigaraksa Satria Tbk.' },
  { symbol: 'TIFA', name: 'KDB Tifa Finance Tbk.' },
  { symbol: 'TINS', name: 'Timah Tbk.' },
  { symbol: 'TIRA', name: 'Tira Austenite Tbk' },
  { symbol: 'TIRT', name: 'Tirta Mahakam Resources Tbk' },
  { symbol: 'TKIM', name: 'Pabrik Kertas Tjiwi Kimia Tbk.' },
  { symbol: 'TLKM', name: 'Telkom Indonesia (Persero) Tbk' },
  { symbol: 'TMAS', name: 'Temas Tbk.' },
  { symbol: 'TMPO', name: 'Tempo Intimedia Tbk.' },
  { symbol: 'TOBA', name: 'TBS Energi Utama Tbk.' },
  { symbol: 'TOTL', name: 'Total Bangun Persada Tbk.' },
  { symbol: 'TOTO', name: 'Surya Toto Indonesia Tbk.' },
  { symbol: 'TOWR', name: 'Sarana Menara Nusantara Tbk.' },
  { symbol: 'TPIA', name: 'Chandra Asri Pacific Tbk.' },
  { symbol: 'TPMA', name: 'Trans Power Marine Tbk.' },
  { symbol: 'TRAM', name: 'Trada Alam Minera Tbk.' },
  { symbol: 'TRIL', name: 'Triwira Insanlestari Tbk.' },
  { symbol: 'TRIM', name: 'Trimegah Sekuritas Indonesia T' },
  { symbol: 'TRIO', name: 'Trikomsel Oke Tbk.' },
  { symbol: 'TRIS', name: 'Trisula International Tbk.' },
  { symbol: 'TRST', name: 'Trias Sentosa Tbk.' },
  { symbol: 'TRUS', name: 'Trust Finance Indonesia Tbk' },
  { symbol: 'TSPC', name: 'Tempo Scan Pacific Tbk.' },
  { symbol: 'ULTJ', name: 'Ultrajaya Milk Industry & Trad' },
  { symbol: 'UNIC', name: 'Unggul Indah Cahaya Tbk.' },
  { symbol: 'UNIT', name: 'Nusantara Inti Corpora Tbk' },
  { symbol: 'UNSP', name: 'Bakrie Sumatera Plantations Tb' },
  { symbol: 'UNTR', name: 'United Tractors Tbk.' },
  { symbol: 'UNVR', name: 'Unilever Indonesia Tbk.' },
  { symbol: 'VICO', name: 'Victoria Investama Tbk.' },
  { symbol: 'VINS', name: 'Victoria Insurance Tbk.' },
  { symbol: 'VIVA', name: 'Visi Media Asia Tbk.' },
  { symbol: 'VOKS', name: 'Voksel Electric Tbk.' },
  { symbol: 'VRNA', name: 'Mizuho Leasing Indonesia Tbk.' },
  { symbol: 'WAPO', name: 'Wahana Pronatural Tbk.' },
  { symbol: 'WEHA', name: 'WEHA Transportasi Indonesia Tb' },
  { symbol: 'WICO', name: 'Wicaksana Overseas Internation' },
  { symbol: 'WIIM', name: 'Wismilak Inti Makmur Tbk.' },
  { symbol: 'WIKA', name: 'Wijaya Karya (Persero) Tbk.' },
  { symbol: 'WINS', name: 'Wintermar Offshore Marine Tbk.' },
  { symbol: 'WOMF', name: 'Wahana Ottomitra Multiartha Tb' },
  { symbol: 'WSKT', name: 'Waskita Karya (Persero) Tbk.' },
  { symbol: 'WTON', name: 'Wijaya Karya Beton Tbk.' },
  { symbol: 'YPAS', name: 'Yanaprima Hastapersada Tbk' },
  { symbol: 'YULE', name: 'Yulie Sekuritas Indonesia Tbk.' },
  { symbol: 'ZBRA', name: 'Dosni Roha Indonesia Tbk.' },
  { symbol: 'SHIP', name: 'Sillo Maritime Perdana Tbk.' },
  { symbol: 'CASA', name: 'Capital Financial Indonesia Tb' },
  { symbol: 'DAYA', name: 'Duta Intidaya Tbk.' },
  { symbol: 'DPUM', name: 'Dua Putra Utama Makmur Tbk.' },
  { symbol: 'IDPR', name: 'Indonesia Pondasi Raya Tbk.' },
  { symbol: 'JGLE', name: 'Graha Andrasentra Propertindo ' },
  { symbol: 'KINO', name: 'Kino Indonesia Tbk.' },
  { symbol: 'MARI', name: 'Mahaka Radio Integra Tbk.' },
  { symbol: 'MKNT', name: 'Mitra Komunikasi Nusantara Tbk' },
  { symbol: 'MTRA', name: 'Mitra Pemuda Tbk.' },
  { symbol: 'OASA', name: 'Maharaksa Biru Energi Tbk.' },
  { symbol: 'POWR', name: 'Cikarang Listrindo Tbk.' },
  { symbol: 'INCF', name: 'Indo Komoditi Korpora Tbk.' },
  { symbol: 'WSBP', name: 'Waskita Beton Precast Tbk.' },
  { symbol: 'PBSA', name: 'Paramita Bangun Sarana Tbk.' },
  { symbol: 'PRDA', name: 'Prodia Widyahusada Tbk.' },
  { symbol: 'BOGA', name: 'Bintang Oto Global Tbk.' },
  { symbol: 'BRIS', name: 'Bank Syariah Indonesia Tbk.' },
  { symbol: 'PORT', name: 'Nusantara Pelabuhan Handal Tbk' },
  { symbol: 'CARS', name: 'Industri dan Perdagangan Bintr' },
  { symbol: 'MINA', name: 'Sanurhasta Mitra Tbk.' },
  { symbol: 'FORZ', name: 'Forza Land Indonesia Tbk.' },
  { symbol: 'CLEO', name: 'Sariguna Primatirta Tbk.' },
  { symbol: 'TAMU', name: 'Pelayaran Tamarin Samudra Tbk.' },
  { symbol: 'CSIS', name: 'Cahayasakti Investindo Sukses ' },
  { symbol: 'TGRA', name: 'Terregra Asia Energy Tbk.' },
  { symbol: 'FIRE', name: 'Alfa Energi Investama Tbk.' },
  { symbol: 'TOPS', name: 'Totalindo Eka Persada Tbk.' },
  { symbol: 'KMTR', name: 'Kirana Megatara Tbk.' },
  { symbol: 'ARMY', name: 'Armidian Karyatama Tbk.' },
  { symbol: 'MAPB', name: 'MAP Boga Adiperkasa Tbk.' },
  { symbol: 'WOOD', name: 'Integra Indocabinet Tbk.' },
  { symbol: 'HRTA', name: 'Hartadinata Abadi Tbk.' },
  { symbol: 'MABA', name: 'Marga Abhinaya Abadi Tbk.' },
  { symbol: 'HOKI', name: 'Buyung Poetra Sembada Tbk.' },
  { symbol: 'MPOW', name: 'Megapower Makmur Tbk.' },
  { symbol: 'MARK', name: 'Mark Dynamics Indonesia Tbk.' },
  { symbol: 'NASA', name: 'Andalan Perkasa Abadi Tbk.' },
  { symbol: 'MDKI', name: 'Emdeki Utama Tbk.' },
  { symbol: 'BELL', name: 'Trisula Textile Industries Tbk' },
  { symbol: 'KIOS', name: 'Kioson Komersial Indonesia Tbk' },
  { symbol: 'GMFI', name: 'Garuda Maintenance Facility Ae' },
  { symbol: 'MTWI', name: 'Malacca Trust Wuwungan Insuran' },
  { symbol: 'ZINC', name: 'Kapuas Prima Coal Tbk.' },
  { symbol: 'MCAS', name: 'M Cash Integrasi Tbk.' },
  { symbol: 'PPRE', name: 'PP Presisi Tbk.' },
  { symbol: 'WEGE', name: 'Wijaya Karya Bangunan Gedung T' },
  { symbol: 'PSSI', name: 'IMC Pelita Logistik Tbk.' },
  { symbol: 'MORA', name: 'Mora Telematika Indonesia Tbk.' },
  { symbol: 'DWGL', name: 'Dwi Guna Laksana Tbk.' },
  { symbol: 'PBID', name: 'Panca Budi Idaman Tbk.' },
  { symbol: 'JMAS', name: 'Asuransi Jiwa Syariah Jasa Mit' },
  { symbol: 'CAMP', name: 'Campina Ice Cream Industry Tbk' },
  { symbol: 'IPCM', name: 'Jasa Armada Indonesia Tbk.' },
  { symbol: 'PCAR', name: 'Prima Cakrawala Abadi Tbk.' },
  { symbol: 'LCKM', name: 'LCK Global Kedaton Tbk.' },
  { symbol: 'BOSS', name: 'Borneo Olah Sarana Sukses Tbk.' },
  { symbol: 'HELI', name: 'Jaya Trishindo Tbk.' },
  { symbol: 'JSKY', name: 'Sky Energy Indonesia Tbk.' },
  { symbol: 'INPS', name: 'Indah Prakasa Sentosa Tbk.' },
  { symbol: 'GHON', name: 'Gihon Telekomunikasi Indonesia' },
  { symbol: 'TDPM', name: 'Tianrong Chemicals Industry Tb' },
  { symbol: 'DFAM', name: 'Dafam Property Indonesia Tbk.' },
  { symbol: 'NICK', name: 'Charnic Capital Tbk.' },
  { symbol: 'BTPS', name: 'Bank BTPN Syariah Tbk.' },
  { symbol: 'SPTO', name: 'Surya Pertiwi Tbk.' },
  { symbol: 'PRIM', name: 'Royal Prima Tbk.' },
  { symbol: 'HEAL', name: 'Medikaloka Hermina Tbk.' },
  { symbol: 'TRUK', name: 'Guna Timur Raya Tbk.' },
  { symbol: 'PZZA', name: 'Sarimelati Kencana Tbk.' },
  { symbol: 'TUGU', name: 'Asuransi Tugu Pratama Indonesi' },
  { symbol: 'MSIN', name: 'MNC Digital Entertainment Tbk.' },
  { symbol: 'SWAT', name: 'Sriwahana Adityakarta Tbk.' },
  { symbol: 'KPAL', name: 'Steadfast Marine Tbk.' },
  { symbol: 'TNCA', name: 'Trimuda Nuansa Citra Tbk.' },
  { symbol: 'MAPA', name: 'Map Aktif Adiperkasa Tbk.' },
  { symbol: 'TCPI', name: 'Transcoal Pacific Tbk.' },
  { symbol: 'IPCC', name: 'Indonesia Kendaraan Terminal T' },
  { symbol: 'RISE', name: 'Jaya Sukses Makmur Sentosa Tbk' },
  { symbol: 'BPTR', name: 'Batavia Prosperindo Trans Tbk.' },
  { symbol: 'POLL', name: 'Pollux Properties Indonesia Tb' },
  { symbol: 'NFCX', name: 'NFC Indonesia Tbk.' },
  { symbol: 'MGRO', name: 'Mahkota Group Tbk.' },
  { symbol: 'NUSA', name: 'Sinergi Megah Internusa Tbk.' },
  { symbol: 'FILM', name: 'MD Entertainment Tbk.' },
  { symbol: 'ANDI', name: 'Andira Agro Tbk.' },
  { symbol: 'LAND', name: 'Trimitra Propertindo Tbk.' },
  { symbol: 'MOLI', name: 'Madusari Murni Indah Tbk.' },
  { symbol: 'PANI', name: 'Pantai Indah Kapuk Dua Tbk.' },
  { symbol: 'DIGI', name: 'Arkadia Digital Media Tbk.' },
  { symbol: 'CITY', name: 'Natura City Developments Tbk.' },
  { symbol: 'SAPX', name: 'Satria Antaran Prima Tbk.' },
  { symbol: 'KPAS', name: 'Cottonindo Ariesta Tbk.' },
  { symbol: 'SURE', name: 'Super Energy Tbk.' },
  { symbol: 'HKMU', name: 'HK Metals Utama Tbk.' },
  { symbol: 'MPRO', name: 'Maha Properti Indonesia Tbk.' },
  { symbol: 'DUCK', name: 'Jaya Bersama Indo Tbk.' },
  { symbol: 'GOOD', name: 'Garudafood Putra Putri Jaya Tb' },
  { symbol: 'SKRN', name: 'Superkrane Mitra Utama Tbk.' },
  { symbol: 'YELO', name: 'Yelooo Integra Datanet Tbk.' },
  { symbol: 'CAKK', name: 'Cahayaputra Asa Keramik Tbk.' },
  { symbol: 'SATU', name: 'Kota Satu Properti Tbk.' },
  { symbol: 'ZONE', name: 'Mega Perintis Tbk.' },
  { symbol: 'PEHA', name: 'Phapros Tbk.' },
  { symbol: 'FOOD', name: 'Sentra Food Indonesia Tbk.' },
  { symbol: 'BEEF', name: 'Estika Tata Tiara Tbk.' },
  { symbol: 'POLI', name: 'Pollux Hotels Group Tbk.' },
  { symbol: 'CLAY', name: 'Citra Putra Realty Tbk.' },
  { symbol: 'NATO', name: 'Surya Permata Andalan Tbk.' },
  { symbol: 'JAYA', name: 'Armada Berjaya Trans Tbk.' },
  { symbol: 'COCO', name: 'Wahana Interfood Nusantara Tbk' },
  { symbol: 'MTPS', name: 'Meta Epsi Tbk.' },
  { symbol: 'CPRI', name: 'Capri Nusa Satu Properti Tbk.' },
  { symbol: 'HRME', name: 'Menteng Heritage Realty Tbk.' },
  { symbol: 'POSA', name: 'Bliss Properti Indonesia Tbk.' },
  { symbol: 'JAST', name: 'Jasnita Telekomindo Tbk.' },
  { symbol: 'FITT', name: 'Hotel Fitra International Tbk.' },
  { symbol: 'BOLA', name: 'Bali Bintang Sejahtera Tbk.' },
  { symbol: 'CCSI', name: 'Communication Cable Systems In' },
  { symbol: 'SFAN', name: 'Surya Fajar Capital Tbk.' },
  { symbol: 'POLU', name: 'Golden Flower Tbk.' },
  { symbol: 'KJEN', name: 'Krida Jaringan Nusantara Tbk.' },
  { symbol: 'KAYU', name: 'Darmi Bersaudara Tbk.' },
  { symbol: 'ITIC', name: 'Indonesian Tobacco Tbk.' },
  { symbol: 'PAMG', name: 'Bima Sakti Pertiwi Tbk.' },
  { symbol: 'IPTV', name: 'MNC Vision Networks Tbk.' },
  { symbol: 'BLUE', name: 'Berkah Prima Perkasa Tbk.' },
  { symbol: 'ENVY', name: 'Envy Technologies Indonesia Tb' },
  { symbol: 'EAST', name: 'Eastparc Hotel Tbk.' },
  { symbol: 'LIFE', name: 'MSIG Life Insurance Indonesia ' },
  { symbol: 'FUJI', name: 'Fuji Finance Indonesia Tbk.' },
  { symbol: 'KOTA', name: 'DMS Propertindo Tbk.' },
  { symbol: 'INOV', name: 'Inocycle Technology Group Tbk.' },
  { symbol: 'ARKA', name: 'Arkha Jayanti Persada Tbk.' },
  { symbol: 'SMKL', name: 'Satyamitra Kemas Lestari Tbk.' },
  { symbol: 'HDIT', name: 'Hensel Davest Indonesia Tbk.' },
  { symbol: 'KEEN', name: 'Kencana Energi Lestari Tbk.' },
  { symbol: 'BAPI', name: 'Bhakti Agung Propertindo Tbk.' },
  { symbol: 'TFAS', name: 'Telefast Indonesia Tbk.' },
  { symbol: 'GGRP', name: 'Gunung Raja Paksi Tbk.' },
  { symbol: 'OPMS', name: 'Optima Prima Metal Sinergi Tbk' },
  { symbol: 'NZIA', name: 'Nusantara Almazia Tbk.' },
  { symbol: 'SLIS', name: 'Gaya Abadi Sempurna Tbk.' },
  { symbol: 'PURE', name: 'Trinitan Metals and Minerals T' },
  { symbol: 'IRRA', name: 'Itama Ranoraya Tbk.' },
  { symbol: 'DMMX', name: 'Digital Mediatama Maxima Tbk.' },
  { symbol: 'SINI', name: 'Singaraja Putra Tbk.' },
  { symbol: 'WOWS', name: 'Ginting Jaya Energi Tbk.' },
  { symbol: 'ESIP', name: 'Sinergi Inti Plastindo Tbk.' },
  { symbol: 'TEBE', name: 'Dana Brata Luhur Tbk.' },
  { symbol: 'KEJU', name: 'Mulia Boga Raya Tbk.' },
  { symbol: 'PSGO', name: 'Palma Serasih Tbk.' },
  { symbol: 'AGAR', name: 'Asia Sejahtera Mina Tbk.' },
  { symbol: 'IFSH', name: 'Ifishdeco Tbk.' },
  { symbol: 'REAL', name: 'Repower Asia Indonesia Tbk.' },
  { symbol: 'IFII', name: 'Indonesia Fibreboard Industry ' },
  { symbol: 'PMJS', name: 'Putra Mandiri Jembar Tbk.' },
  { symbol: 'UCID', name: 'Uni-Charm Indonesia Tbk.' },
  { symbol: 'GLVA', name: 'Galva Technologies Tbk.' },
  { symbol: 'PGJO', name: 'Tourindo Guide Indonesia Tbk.' },
  { symbol: 'AMAR', name: 'Bank Amar Indonesia Tbk.' },
  { symbol: 'CSRA', name: 'Cisadane Sawit Raya Tbk.' },
  { symbol: 'INDO', name: 'Royalindo Investa Wijaya Tbk.' },
  { symbol: 'AMOR', name: 'Ashmore Asset Management Indon' },
  { symbol: 'TRIN', name: 'Perintis Triniti Properti Tbk.' },
  { symbol: 'DMND', name: 'Diamond Food Indonesia Tbk.' },
  { symbol: 'PURA', name: 'Putra Rajawali Kencana Tbk.' },
  { symbol: 'PTPW', name: 'Pratama Widya Tbk.' },
  { symbol: 'TAMA', name: 'Lancartama Sejati Tbk.' },
  { symbol: 'IKAN', name: 'Era Mandiri Cemerlang Tbk.' },
  { symbol: 'AYLS', name: 'Agro Yasa Lestari Tbk.' },
  { symbol: 'DADA', name: 'Diamond Citra Propertindo Tbk.' },
  { symbol: 'ASPI', name: 'Andalan Sakti Primaindo Tbk.' },
  { symbol: 'ESTA', name: 'Esta Multi Usaha Tbk.' },
  { symbol: 'BESS', name: 'Batulicin Nusantara Maritim Tb' },
  { symbol: 'CSMI', name: 'Cipta Selera Murni Tbk.' },
  { symbol: 'BBSS', name: 'Bumi Benowo Sukses Sejahtera T' },
  { symbol: 'BHAT', name: 'Bhakti Multi Artha Tbk.' },
  { symbol: 'CASH', name: 'Cashlez Worldwide Indonesia Tb' },
  { symbol: 'TECH', name: 'Indosterling Technomedia Tbk.' },
  { symbol: 'EPAC', name: 'Megalestari Epack Sentosaraya ' },
  { symbol: 'UANG', name: 'Pakuan Tbk.' },
  { symbol: 'PGUN', name: 'Pradiksi Gunatama Tbk.' },
  { symbol: 'SOFA', name: 'Boston Furniture Industries Tb' },
  { symbol: 'PPGL', name: 'Prima Globalindo Logistik Tbk.' },
  { symbol: 'TOYS', name: 'Sunindo Adipersada Tbk.' },
  { symbol: 'SGER', name: 'Sumber Global Energy Tbk.' },
  { symbol: 'TRJA', name: 'Transkon Jaya Tbk.' },
  { symbol: 'PNGO', name: 'Pinago Utama Tbk.' },
  { symbol: 'SCNP', name: 'Selaras Citra Nusantara Perkas' },
  { symbol: 'BBSI', name: 'Krom Bank Indonesia Tbk.' },
  { symbol: 'KMDS', name: 'Kurniamitra Duta Sentosa Tbk.' },
  { symbol: 'PURI', name: 'Puri Global Sukses Tbk.' },
  { symbol: 'SOHO', name: 'Soho Global Health Tbk.' },
  { symbol: 'HOMI', name: 'Grand House Mulia Tbk.' },
  { symbol: 'ROCK', name: 'Rockfields Properti Indonesia ' },
  { symbol: 'ENZO', name: 'Morenzo Abadi Perkasa Tbk.' },
  { symbol: 'PLAN', name: 'Planet Properindo Jaya Tbk.' },
  { symbol: 'PTDU', name: 'Djasa Ubersakti Tbk.' },
  { symbol: 'ATAP', name: 'Trimitra Prawara Goldland Tbk.' },
  { symbol: 'VICI', name: 'Victoria Care Indonesia Tbk.' },
  { symbol: 'PMMP', name: 'Panca Mitra Multiperdana Tbk.' },
  { symbol: 'WIFI', name: 'Solusi Sinergi Digital Tbk.' },
  { symbol: 'FAPA', name: 'FAP Agri Tbk.' },
  { symbol: 'DCII', name: 'DCI Indonesia Tbk.' },
  { symbol: 'KETR', name: 'Ketrosden Triasmitra Tbk.' },
  { symbol: 'DGNS', name: 'Diagnos Laboratorium Utama Tbk' },
  { symbol: 'UFOE', name: 'Damai Sejahtera Abadi Tbk.' },
  { symbol: 'BANK', name: 'Bank Aladin Syariah Tbk.' },
  { symbol: 'WMUU', name: 'Widodo Makmur Unggas Tbk.' },
  { symbol: 'EDGE', name: 'Indointernet Tbk.' },
  { symbol: 'UNIQ', name: 'Ulima Nitra Tbk.' },
  { symbol: 'BEBS', name: 'Berkah Beton Sadaya Tbk.' },
  { symbol: 'SNLK', name: 'Sunter Lakeside Hotel Tbk.' },
  { symbol: 'ZYRX', name: 'Zyrexindo Mandiri Buana Tbk.' },
  { symbol: 'LFLO', name: 'Imago Mulia Persada Tbk.' },
  { symbol: 'FIMP', name: 'Fimperkasa Utama Tbk.' },
  { symbol: 'TAPG', name: 'Triputra Agro Persada Tbk.' },
  { symbol: 'NPGF', name: 'Nusa Palapa Gemilang Tbk.' },
  { symbol: 'LUCY', name: 'Lima Dua Lima Tiga Tbk.' },
  { symbol: 'ADCP', name: 'Adhi Commuter Properti Tbk.' },
  { symbol: 'HOPE', name: 'Harapan Duta Pertiwi Tbk.' },
  { symbol: 'MGLV', name: 'Panca Anugrah Wisesa Tbk.' },
  { symbol: 'TRUE', name: 'Triniti Dinamik Tbk.' },
  { symbol: 'LABA', name: 'Green Power Group Tbk.' },
  { symbol: 'ARCI', name: 'Archi Indonesia Tbk.' },
  { symbol: 'IPAC', name: 'Era Graharealty Tbk.' },
  { symbol: 'MASB', name: 'Bank Multiarta Sentosa Tbk.' },
  { symbol: 'BMHS', name: 'Bundamedik Tbk.' },
  { symbol: 'FLMC', name: 'Falmaco Nonwoven Industri Tbk.' },
  { symbol: 'NICL', name: 'PAM Mineral Tbk.' },
  { symbol: 'UVCR', name: 'Trimegah Karya Pratama Tbk.' },
  { symbol: 'BUKA', name: 'Bukalapak.com Tbk.' },
  { symbol: 'HAIS', name: 'Hasnur Internasional Shipping ' },
  { symbol: 'OILS', name: 'Indo Oil Perkasa Tbk.' },
  { symbol: 'GPSO', name: 'Geoprima Solusi Tbk.' },
  { symbol: 'MCOL', name: 'Prima Andalan Mandiri Tbk.' },
  { symbol: 'RSGK', name: 'Kedoya Adyaraya Tbk.' },
  { symbol: 'RUNS', name: 'Global Sukses Solusi Tbk.' },
  { symbol: 'SBMA', name: 'Surya Biru Murni Acetylene Tbk' },
  { symbol: 'CMNT', name: 'Cemindo Gemilang Tbk.' },
  { symbol: 'GTSI', name: 'GTS Internasional Tbk.' },
  { symbol: 'IDEA', name: 'Idea Indonesia Akademi Tbk.' },
  { symbol: 'KUAS', name: 'Ace Oldfields Tbk.' },
  { symbol: 'BOBA', name: 'Formosa Ingredient Factory Tbk' },
  { symbol: 'MTEL', name: 'Dayamitra Telekomunikasi Tbk.' },
  { symbol: 'DEPO', name: 'Caturkarda Depo Bangunan Tbk.' },
  { symbol: 'BINO', name: 'Perma Plasindo Tbk.' },
  { symbol: 'CMRY', name: 'Cisarua Mountain Dairy Tbk.' },
  { symbol: 'WGSH', name: 'Wira Global Solusi Tbk.' },
  { symbol: 'TAYS', name: 'Jaya Swarasa Agung Tbk.' },
  { symbol: 'WMPP', name: 'Widodo Makmur Perkasa Tbk.' },
  { symbol: 'RMKE', name: 'RMK Energy Tbk.' },
  { symbol: 'OBMD', name: 'OBM Drilchem Tbk.' },
  { symbol: 'AVIA', name: 'Avia Avian Tbk.' },
  { symbol: 'IPPE', name: 'Indo Pureco Pratama Tbk.' },
  { symbol: 'NASI', name: 'Wahana Inti Makmur Tbk.' },
  { symbol: 'BSML', name: 'Bintang Samudera Mandiri Lines' },
  { symbol: 'DRMA', name: 'Dharma Polimetal Tbk.' },
  { symbol: 'ADMR', name: 'Adaro Minerals Indonesia Tbk.' },
  { symbol: 'SEMA', name: 'Semacom Integrated Tbk.' },
  { symbol: 'ASLC', name: 'Autopedia Sukses Lestari Tbk.' },
  { symbol: 'NETV', name: 'MDTV Media Technologies Tbk.' },
  { symbol: 'BAUT', name: 'Mitra Angkasa Sejahtera Tbk.' },
  { symbol: 'ENAK', name: 'Champ Resto Indonesia Tbk.' },
  { symbol: 'NTBK', name: 'Nusatama Berkah Tbk.' },
  { symbol: 'SMKM', name: 'Sumber Mas Konstruksi Tbk.' },
  { symbol: 'STAA', name: 'Sumber Tani Agung Resources Tb' },
  { symbol: 'NANO', name: 'Nanotech Indonesia Global Tbk.' },
  { symbol: 'BIKE', name: 'Sepeda Bersama Indonesia Tbk.' },
  { symbol: 'WIRG', name: 'WIR ASIA Tbk.' },
  { symbol: 'SICO', name: 'Sigma Energy Compressindo Tbk.' },
  { symbol: 'GOTO', name: 'GoTo Gojek Tokopedia Tbk.' },
  { symbol: 'TLDN', name: 'Teladan Prima Agro Tbk.' },
  { symbol: 'MTMH', name: 'Murni Sadar Tbk.' },
  { symbol: 'WINR', name: 'Winner Nusantara Jaya Tbk.' },
  { symbol: 'IBOS', name: 'Indo Boga Sukses Tbk.' },
  { symbol: 'OLIV', name: 'Oscar Mitra Sukses Sejahtera T' },
  { symbol: 'ASHA', name: 'Cilacap Samudera Fishing Indus' },
  { symbol: 'SWID', name: 'Saraswanti Indoland Developmen' },
  { symbol: 'TRGU', name: 'Cerestar Indonesia Tbk.' },
  { symbol: 'ARKO', name: 'Arkora Hydro Tbk.' },
  { symbol: 'CHEM', name: 'Chemstar Indonesia Tbk.' },
  { symbol: 'DEWI', name: 'Dewi Shri Farmindo Tbk.' },
  { symbol: 'AXIO', name: 'Tera Data Indonusa Tbk.' },
  { symbol: 'KRYA', name: 'Bangun Karya Perkasa Jaya Tbk.' },
  { symbol: 'HATM', name: 'Habco Trans Maritima Tbk.' },
  { symbol: 'RCCC', name: 'Utama Radar Cahaya Tbk.' },
  { symbol: 'GULA', name: 'Aman Agrindo Tbk.' },
  { symbol: 'JARR', name: 'Jhonlin Agro Raya Tbk.' },
  { symbol: 'AMMS', name: 'Agung Menjangan Mas Tbk.' },
  { symbol: 'RAFI', name: 'Sari Kreasi Boga Tbk.' },
  { symbol: 'KKES', name: 'Kusuma Kemindo Sentosa Tbk.' },
  { symbol: 'ELPI', name: 'Pelayaran Nasional Ekalya Purn' },
  { symbol: 'EURO', name: 'Estee Gold Feet Tbk.' },
  { symbol: 'KLIN', name: 'Klinko Karya Imaji Tbk.' },
  { symbol: 'TOOL', name: 'Rohartindo Nusantara Luas Tbk.' },
  { symbol: 'BUAH', name: 'Segar Kumala Indonesia Tbk.' },
  { symbol: 'CRAB', name: 'Toba Surimi Industries Tbk.' },
  { symbol: 'MEDS', name: 'Hetzer Medical Indonesia Tbk.' },
  { symbol: 'COAL', name: 'Black Diamond Resources Tbk.' },
  { symbol: 'PRAY', name: 'Famon Awal Bros Sedaya Tbk.' },
  { symbol: 'CBUT', name: 'Citra Borneo Utama Tbk.' },
  { symbol: 'BELI', name: 'Global Digital Niaga Tbk.' },
  { symbol: 'MKTR', name: 'Menthobi Karyatama Raya Tbk.' },
  { symbol: 'OMED', name: 'Jayamas Medica Industri Tbk.' },
  { symbol: 'BSBK', name: 'Wulandari Bangun Laksana Tbk.' },
  { symbol: 'PDPP', name: 'Primadaya Plastisindo Tbk.' },
  { symbol: 'KDTN', name: 'Puri Sentul Permai Tbk.' },
  { symbol: 'ZATA', name: 'Bersama Zatta Jaya Tbk.' },
  { symbol: 'NINE', name: 'Techno9 Indonesia Tbk.' },
  { symbol: 'MMIX', name: 'Multi Medika Internasional Tbk' },
  { symbol: 'PADA', name: 'Personel Alih Daya Tbk.' },
  { symbol: 'ISAP', name: 'Isra Presisi Indonesia Tbk.' },
  { symbol: 'VTNY', name: 'Venteny Fortuna International ' },
  { symbol: 'SOUL', name: 'Mitra Tirta Buwana Tbk.' },
  { symbol: 'ELIT', name: 'Data Sinergitama Jaya Tbk.' },
  { symbol: 'BEER', name: 'Jobubu Jarum Minahasa Tbk.' },
  { symbol: 'CBPE', name: 'Citra Buana Prasida Tbk.' },
  { symbol: 'SUNI', name: 'Sunindo Pratama Tbk.' },
  { symbol: 'CBRE', name: 'Cakra Buana Resources Energi T' },
  { symbol: 'WINE', name: 'Hatten Bali Tbk.' },
  { symbol: 'BMBL', name: 'Lavender Bina Cendikia Tbk.' },
  { symbol: 'PEVE', name: 'Penta Valent Tbk.' },
  { symbol: 'LAJU', name: 'Jasa Berdikari Logistics Tbk.' },
  { symbol: 'FWCT', name: 'Wijaya Cahaya Timber Tbk.' },
  { symbol: 'NAYZ', name: 'Hassana Boga Sejahtera Tbk.' },
  { symbol: 'IRSX', name: 'Aviana Sinar Abadi Tbk.' },
  { symbol: 'PACK', name: 'Abadi Nusantara Hijau Investam' },
  { symbol: 'VAST', name: 'Vastland Indonesia Tbk.' },
  { symbol: 'CHIP', name: 'Pelita Teknologi Global Tbk.' },
  { symbol: 'HALO', name: 'Haloni Jane Tbk.' },
  { symbol: 'KING', name: 'Hoffmen Cleanindo Tbk.' },
  { symbol: 'PGEO', name: 'Pertamina Geothermal Energy Tb' },
  { symbol: 'FUTR', name: 'Lini Imaji Kreasi Ekosistem Tb' },
  { symbol: 'HILL', name: 'Hillcon Tbk.' },
  { symbol: 'BDKR', name: 'Berdikari Pondasi Perkasa Tbk.' },
  { symbol: 'PTMP', name: 'Mitra Pack Tbk.' },
  { symbol: 'SAGE', name: 'Saptausaha Gemilangindah Tbk.' },
  { symbol: 'TRON', name: 'Teknologi Karya Digital Nusa T' },
  { symbol: 'CUAN', name: 'Petrindo Jaya Kreasi Tbk.' },
  { symbol: 'NSSS', name: 'Nusantara Sawit Sejahtera Tbk.' },
  { symbol: 'GTRA', name: 'Grahaprima Suksesmandiri Tbk.' },
  { symbol: 'HAJJ', name: 'Arsy Buana Travelindo Tbk.' },
  { symbol: 'PIPA', name: 'Multi Makmur Lemindo Tbk.' },
  { symbol: 'NCKL', name: 'Trimegah Bangun Persada Tbk.' },
  { symbol: 'MENN', name: 'Menn Teknologi Indonesia Tbk.' },
  { symbol: 'AWAN', name: 'Era Digital Media Tbk.' },
  { symbol: 'MBMA', name: 'Merdeka Battery Materials Tbk.' },
  { symbol: 'RAAM', name: 'Tripar Multivision Plus Tbk.' },
  { symbol: 'DOOH', name: 'Era Media Sejahtera Tbk.' },
  { symbol: 'JATI', name: 'Informasi Teknologi Indonesia ' },
  { symbol: 'TYRE', name: 'King Tire Indonesia Tbk.' },
  { symbol: 'MPXL', name: 'MPX Logistics International Tb' },
  { symbol: 'SMIL', name: 'Sarana Mitra Luas Tbk.' },
  { symbol: 'KLAS', name: 'Pelayaran Kurnia Lautan Semest' },
  { symbol: 'MAXI', name: 'Maxindo Karya Anugerah Tbk.' },
  { symbol: 'VKTR', name: 'VKTR Teknologi Mobilitas Tbk.' },
  { symbol: 'RELF', name: 'Graha Mitra Asia Tbk.' },
  { symbol: 'AMMN', name: 'Amman Mineral Internasional Tb' },
  { symbol: 'CRSN', name: 'Carsurin Tbk.' },
  { symbol: 'GRPM', name: 'Graha Prima Mentari Tbk.' },
  { symbol: 'WIDI', name: 'Widiant Jaya Krenindo Tbk.' },
  { symbol: 'TGUK', name: 'Platinum Wahab Nusantara Tbk.' },
  { symbol: 'INET', name: 'Sinergi Inti Andalan Prima Tbk' },
  { symbol: 'MAHA', name: 'Mandiri Herindo Adiperkasa Tbk' },
  { symbol: 'RMKO', name: 'Royaltama Mulia Kontraktorindo' },
  { symbol: 'CNMA', name: 'Nusantara Sejahtera Raya Tbk.' },
  { symbol: 'FOLK', name: 'Multi Garam Utama Tbk.' },
  { symbol: 'HBAT', name: 'Minahasa Membangun Hebat Tbk.' },
  { symbol: 'GRIA', name: 'Ingria Pratama Capitalindo Tbk' },
  { symbol: 'PPRI', name: 'Paperocks Indonesia Tbk.' },
  { symbol: 'ERAL', name: 'Sinar Eka Selaras Tbk.' },
  { symbol: 'CYBR', name: 'ITSEC Asia Tbk.' },
  { symbol: 'MUTU', name: 'Mutuagung Lestari Tbk.' },
  { symbol: 'LMAX', name: 'Lupromax Pelumas Indonesia Tbk' },
  { symbol: 'HUMI', name: 'Humpuss Maritim Internasional ' },
  { symbol: 'MSIE', name: 'Multisarana Intan Eduka Tbk.' },
  { symbol: 'RSCH', name: 'Charlie Hospital Semarang Tbk.' },
  { symbol: 'BABY', name: 'Multitrend Indo Tbk.' },
  { symbol: 'AEGS', name: 'Anugerah Spareparts Sejahtera ' },
  { symbol: 'IOTF', name: 'Sumber Sinergi Makmur Tbk.' },
  { symbol: 'KOCI', name: 'Kokoh Exa Nusantara Tbk.' },
  { symbol: 'PTPS', name: 'Pulau Subur Tbk.' },
  { symbol: 'BREN', name: 'Barito Renewables Energy Tbk.' },
  { symbol: 'STRK', name: 'Lovina Beach Brewery Tbk.' },
  { symbol: 'KOKA', name: 'Koka Indonesia Tbk.' },
  { symbol: 'LOPI', name: 'Logisticsplus International Tb' },
  { symbol: 'UDNG', name: 'Agro Bahari Nusantara Tbk.' },
  { symbol: 'RGAS', name: 'Kian Santang Muliatama Tbk.' },
  { symbol: 'MSTI', name: 'Mastersystem Infotama Tbk.' },
  { symbol: 'IKPM', name: 'Ikapharmindo Putramas Tbk.' },
  { symbol: 'AYAM', name: 'Janu Putra Sejahtera Tbk.' },
  { symbol: 'SURI', name: 'Maja Agung Latexindo Tbk.' },
  { symbol: 'ASLI', name: 'Asri Karya Lestari Tbk.' },
  { symbol: 'CGAS', name: 'Citra Nusantara Gemilang Tbk.' },
  { symbol: 'NICE', name: 'Adhi Kartiko Pratama Tbk.' },
  { symbol: 'MSJA', name: 'Multi Spunindo Jaya Tbk.' },
  { symbol: 'SMLE', name: 'Sinergi Multi Lestarindo Tbk.' },
  { symbol: 'ACRO', name: 'Samcro Hyosung Adilestari Tbk.' },
  { symbol: 'MANG', name: 'Manggung Polahraya Tbk.' },
  { symbol: 'GRPH', name: 'Griptha Putra Persada Tbk.' },
  { symbol: 'SMGA', name: 'Sumber Mineral Global Abadi Tb' },
  { symbol: 'UNTD', name: 'Terang Dunia Internusa Tbk.' },
  { symbol: 'TOSK', name: 'Topindo Solusi Komunika Tbk.' },
  { symbol: 'MPIX', name: 'Mitra Pedagang Indonesia Tbk.' },
  { symbol: 'ALII', name: 'Ancara Logistics Indonesia Tbk' },
  { symbol: 'MKAP', name: 'Multikarya Asia Pasifik Raya T' },
  { symbol: 'MEJA', name: 'Harta Djaya Karya Tbk.' },
  { symbol: 'LIVE', name: 'Homeco Victoria Makmur Tbk.' },
  { symbol: 'HYGN', name: 'Ecocare Indo Pasifik Tbk.' },
  { symbol: 'BAIK', name: 'Bersama Mencapai Puncak Tbk.' },
  { symbol: 'VISI', name: 'Satu Visi Putra Tbk.' },
  { symbol: 'AREA', name: 'Dunia Virtual Online Tbk.' },
  { symbol: 'MHKI', name: 'Multi Hanna Kreasindo Tbk.' },
  { symbol: 'ATLA', name: 'Atlantis Subsea Indonesia Tbk.' },
  { symbol: 'DATA', name: 'Remala Abadi Tbk.' },
  { symbol: 'SOLA', name: 'Xolare RCR Energy Tbk.' },
  { symbol: 'BATR', name: 'Benteng Api Technic Tbk.' },
  { symbol: 'SPRE', name: 'Soraya Berjaya Indonesia Tbk.' },
  { symbol: 'PART', name: 'Cipta Perdana Lancar Tbk.' },
  { symbol: 'GOLF', name: 'Intra Golflink Resorts Tbk.' },
  { symbol: 'ISEA', name: 'Indo American Seafoods Tbk.' },
  { symbol: 'BLES', name: 'Superior Prima Sukses Tbk.' },
  { symbol: 'GUNA', name: 'Gunanusa Eramandiri Tbk.' },
  { symbol: 'LABS', name: 'UBC Medical Indonesia Tbk.' },
  { symbol: 'DOSS', name: 'Global Sukses Digital Tbk.' },
  { symbol: 'NEST', name: 'Esta Indonesia Tbk.' },
  { symbol: 'PTMR', name: 'Master Print Tbk.' },
  { symbol: 'VERN', name: 'Verona Indah Pictures Tbk.' },
  { symbol: 'DAAZ', name: 'Daaz Bara Lestari Tbk.' },
  { symbol: 'BOAT', name: 'Newport Marine Services Tbk.' },
  { symbol: 'NAIK', name: 'Adiwarna Anugerah Abadi Tbk.' },
  { symbol: 'AADI', name: 'Adaro Andalan Indonesia Tbk.' },
  { symbol: 'MDIY', name: 'Daya Intiguna Yasa Tbk.' },
  { symbol: 'KSIX', name: 'Kentanix Supra International T' },
  { symbol: 'RATU', name: 'Raharja Energi Cepu Tbk.' },
  { symbol: 'YOII', name: 'Asuransi Digital Bersama Tbk.' },
  { symbol: 'HGII', name: 'Hero Global Investment Tbk.' },
  { symbol: 'BRRC', name: 'Raja Roti Cemerlang Tbk.' },
  { symbol: 'DGWG', name: 'Delta Giri Wacana Tbk.' },
  { symbol: 'CBDK', name: 'Bangun Kosambi Sukses Tbk.' },
  { symbol: 'OBAT', name: 'Brigit Biofarmaka Teknologi Tb' },
  { symbol: 'SOSS', name: 'Shield On Service Tbk.' },
  { symbol: 'DEAL', name: 'Dewata Freightinternational Tb' },
  { symbol: 'POLA', name: 'Pool Advista Finance Tbk.' },
  { symbol: 'DIVA', name: 'Distribusi Voucher Nusantara T' },
  { symbol: 'LUCK', name: 'Sentral Mitra Informatika Tbk.' },
  { symbol: 'URBN', name: 'Urban Jakarta Propertindo Tbk.' },
  { symbol: 'SOTS', name: 'Satria Mega Kencana Tbk.' },
  { symbol: 'AMAN', name: 'Makmur Berkah Amanda Tbk.' },
  { symbol: 'CARE', name: 'Metro Healthcare Indonesia Tbk' },
  { symbol: 'SAMF', name: 'Saraswanti Anugerah Makmur Tbk' },
  { symbol: 'SBAT', name: 'Sejahtera Bintang Abadi Textil' },
  { symbol: 'KBAG', name: 'Karya Bersama Anugerah Tbk.' },
  { symbol: 'CBMF', name: 'Cahaya Bintang Medan Tbk.' },
  { symbol: 'RONY', name: 'Aesler Grup Internasional Tbk.' },
]

export function searchIdxStocks(query, limit = 8) {
  const q = String(query || '').toLowerCase().replace(/^idx:/, '').trim()
  if (!q) return IDX_STOCKS.slice(0, limit)
  return IDX_STOCKS
    .filter((stock) =>
      stock.symbol.toLowerCase().includes(q) ||
      stock.name.toLowerCase().includes(q)
    )
    .slice(0, limit)
}
